apiVersion: v1
kind: Service
metadata:
  name: hello-rsxp-loadbalancer
spec:
  selector:
    app: hello-rsxp
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 9000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-rsxp
spec:
  selector:
    matchLabels:
      app: hello-rsxp
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-rsxp
    spec:
      containers:
      - name: hello-rsxp
        image: rsxp_api
        imagePullPolicy: Never
        ports:
        - containerPort: 9000